language: node_js
node_js:
  - "node"

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: true
  on:
    branch: master