language: node_js
node_js:
  - "node"

cache:
  directories:
  - node_modules

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
#  local_dir: dist readd this when react
  keep-history: true
  on:
    branch: master